### ISSUE TITLE
Where can I find the pretrained weight of maskdino ?

### ISSUE THREAD

**Issue by Enyu-Liu** [hustvl/Symphonies#11]
Thank you for your excellent job! I wonder to know where can I find the pretrained weight of maskdino used in encoder part. I cannot find it in both maskdino github and mmdet. 
```
encoder:
    type: MMDetWrapper
    config_path: maskdino/configs/maskdino_r50_8xb2-panoptic-export.py
    custom_imports: maskdino
    checkpoint_path: ../../backups/maskdino_r50_50e_300q_panoptic_pq53.0.pth  
```
